---
title: "Neotropical Mammals"
format: 
  dashboard:
    orientation: columns
---

```{r}
#| echo: false
#| output: false
#| warning: false

library(tidyverse)
library(crosstalk)
library(reactable)
library(leaflet)
library(summarywidget)
```

```{r}
neo_mamm <- read.csv("files/NEOTROPICAL_CARNIVORES_DATASET_REDUCED.csv")

neo_mamm <- neo_mamm %>%
  mutate(COL_START_YR = case_when(grepl("<", COL_START_YR) ~ substring(neo_mamm$COL_START_YR, 2, 5)),
         COL_START_YR = as.numeric(COL_START_YR))


```

```{r}
shared_neo <- neo_mamm %>%
  select(SPECIES, GENUS, FAMILY, LONG_X, LAT_Y, MUNICIPALITY, STATE, COUNTRY, PRECISION_m, METHOD, COL_START_YR)
  
shared_neo <- SharedData$new(shared_neo, group = "Mamm")

shared_species <- neo_mamm %>%
  select(SPECIES) %>%
  unique() %>%
  SharedData$new(group = "Mamm")
```

## {.sidebar}
```{r FILTROS}
filter_select("SPECIES", "Species", shared_neo, ~SPECIES)
filter_select("GENUS", "Genus", shared_neo, ~GENUS)
filter_select("FAMILY", "Family", shared_neo, ~FAMILY)

```   


## Column{.fill}


### Row {height=20%}

#### Column
```{r CARDS 1}

library(bslib)
library(bsicons)
value_box(
  title = "Records",
  value = summarywidget(shared_neo),
  showcase = bsicons::bs_icon("search"),
  theme = "primary"
)
```

#### Column
```{r CARDS 2}

library(bslib)
library(bsicons)
value_box(
  title = "Records",
  value = summarywidget(shared_species),
  showcase = bsicons::bs_icon("search"),
  theme = "primary"
)
```



### Row {height=80%}

#### Column {.tabset}

```{r}
#| echo: false
#| title: Species Map

map <- leaflet(shared_neo) %>%

  addTiles() %>%

    addCircleMarkers(lng = ~LONG_X,
                   lat = ~LAT_Y,
                   popup = ~SPECIES)

map
```

```{r}
#| echo: false
#| title: Species table

#create interactive table using reactable

shared_neo %>%
  reactable(
    columns = list(
                    SPECIES = colDef(name = "Species"),
                    LONG_X = colDef(name = "Longitude"),
                    LAT_Y = colDef(name = "Latitude")),
    
    filterable = TRUE,
    
    bordered = TRUE,
    
    highlight = TRUE,
    
    defaultPageSize = 5
  )
```

## Column {.fill}

``` {r}

neo_mamm %>%
  select(SPECIES) %>%
  group_by(SPECIES) %>%
  summarise(n = n()) %>%
  ggplot(aes(n)) +
    geom_histogram() +
    labs(
      x = "Number of records of each species",
      y = "Count"
    ) +
    theme_bw()

```

``` {r}
neo_mamm %>%
  select(COL_END_YR) %>%
  group_by(COL_END_YR) %>%
  filter(!grepl("<", COL_END_YR)) %>%
  summarise(n = n()) %>%
  mutate(Year = as.numeric(COL_END_YR)) %>%
  ggplot() +
    geom_line(aes(x = Year, y = n)) +
    scale_y_continuous(limits = c(0, 10000)) +
    labs(
      y = "Number of records"
    ) +
    theme_bw()
  



```
